import Head from 'next/head'
import { Domain } from '../../domain'

export default function CityDirectory({ lots }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {lots && lots.map(lot => (
        JSON.stringify(lot)
      ))}
    </div>
  )
}

export async function getServerSideProps({ params: { locationName } }) {
  try {
    const domain = Domain.create()
    const { postal_code } = await domain.GetLocationByNameUseCase.execute({ locationName })
    const { lotsEntityList } = await domain.GetLotListByPostalCodesUseCase.execute({ locationPCS: postal_code })
    return {
      props: {
        lots: lotsEntityList
      }
    }
  } catch (err) {
    console.error('CityDirectory: ', err)
    return {
      props: {
        lots: []
      }
    }
  }
}
