import Head from 'next/head'
import LocationsSuggest from '../components/LocationsSuggest'
import { Domain } from '../domain'

export default function Home({ lots }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {lots && lots.map(lot => (
        JSON.stringify(lot)
      ))}

      <LocationsSuggest />
    </div>
  )
}

export async function getServerSideProps(context) {
  const domain = Domain.create()
  const locationPC = '08016'
  const { lotsEntityList } = await domain.GetLotListByPostalCodeUseCase.execute({ locationPC })
  return {
    props: {
      lots: lotsEntityList
    }
  }
}
